name: limited_features_sample
use_wandb: True

path:
  root: /home/seito/ssd1/activitynet_captions
  feature: ["features/resnet", "features/flow"]
  annotation: captions
  output: ../../out
  submission_file: submission.json

hyperparam:
  attention: True
  tokenizer:
    min_freq: 5
    max_len: 30
  optimization:
    lr: 0.0001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.
  loss_weight:
    XELoss: 1.
    DSLoss: 1.
  feature:
    dim: 3072
  rnn:
    word_emb_dim: 300
    memory_dim: 512
    dropout_prob: 0.5
    scheduled_sampling_prob: 0
  misc:
    max_epoch: 20
    num_worker: 4
    gpu_ids: [0]
    batch_size: 4
    val_samples: 3000
    # set to 0 if making nondeterministic
    random_seed: 0
