name: lr_5
use_wandb: True

path:
  root: /home/seito/ssd1/dsets/activitynet_captions
  feature: [ "features/r50_k700", "features/sf152nl_k700/motion", "features/sf152nl_k700/semantic", "features/resnet", "features/flow" ]
  annotation: captions
  output: ../../out
  submission_file: submission.json

hyperparam:
  attention: True
  tokenizer:
    min_freq: 5
    max_len: 30
  optimization:
    lr: 0.0005
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.
  loss_weight:
    XELoss: 1.
    DSLoss: 1.
  feature:
    dim: 7424
  rnn:
    word_emb_dim: 300
    memory_dim: 512
    dropout_prob: 0.5
    scheduled_sampling_prob: 0
  misc:
    max_epoch: 20
    num_worker: 4
    gpu_ids: [0]
    batch_size: 32
    val_samples: 3000
    random_seed: 42
