name: debug_concurrent
use_wandb: False

path:
  root: /home/seito/ssd2/activitynet
  feature: features/resnet
  annotation: captions
  output: ../../out
  submission_file: submission.json

rnn:
  name: LSTM

optim:
  name: Adam
  lr: 0.0001
  beta1: 0.9
  beta2: 0.999
  weight_decay: 0.00001

dim:
  B: 32
  D: 2048
  E: 300
  M_1: 512
  M_2: 1024
  max_actions: 15
  max_caption_len: 30

hyp:
  dropout: 0.3
  ss_prob: 0.
  min_freq: 5
  gpu_ids: [3]

misc:
  num_workers: 8
  max_epoch: 20
  val_samples: 1000
  random_seed: 0
